config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated :user do
    root 'domains/domains#dashboard', as: :authenticated_root
  end

  root to: 'pages#welcome'

  scope module: 'domains' do
    resources :domains do
    resources :emails, shallow: true 
    end
  end

  get 'refresh/:id', to: "domains/domains#refresh", as: 'refresh_domain'
  get 'get_inside_mail/:id', to: "domains/emails#get_inside_mail", as: 'get_inside_mail'
  get 'change_block_status/:id', to: "domains/emails#change_block_status", as: 'change_block_status'
  get 'change_domain/:id', to: "domains/domains#change_domain", as: 'change_domain'
  get 'set_current_email/:id', to: "domains/emails#set_current_email", as: 'set_current_email'
  get 'change_tab/:id', to: "domains/domains#change_tab", as: 'change_tab'
  get 'kill_filter/:id', to: "domains/emails#kill_filter", as: 'kill_filter'
  get 'add_filter', to: "domains/emails#add_filter"
  get 'email/new', to: "domains/emails#new", as: 'new_email'
  post 'email/new', to: "domains/emails#create"
  get 'kill_that_mail/:id', to: "domains/emails#kill_that_mail", as: 'kill_that_mail'
  get 'profile', to: "users#profile", as: 'profile'
  get 'delete_domain/:id', to: "domains/domains#destroy", as: 'delete_domain'
  get 'faq', to: "pages#faq", as: 'faq'
  patch 'update_domain/:id', to: "domains/domains#update", as: 'update_domain'
  patch 'update_email/:id', to: "domains/emails#update", as: 'update_email'
  get 'add_alias', to: "domains/emails#add_alias", as: "add_alias"
  get 'kill_alias', to: "domains/emails#kill_alias", as: "kill_alias"

end

app/models/domain.rb
require 'yapdd_api'

class Domain < ApplicationRecord
  belongs_to :user
  has_many :emails
  validates :domainname, :domaintoken, :domaintoken2, presence: true

  def refresh_emails
    self.emails.destroy_all
    self.domain_get_emails
    self.domain_get_image_url
  end

  def domain_get_image_url
    request = RestClient::Request.execute(method: :get, url: "https://pddimp.yandex.ru/api2/admin/domain/logo/check?domain=#{self.domainname}", headers: { PddToken: "#{self.domaintoken2}" })
    self.image = JSON.parse(request)['logo-url']
    if self.image.empty?
      self.image = "https://img-fotki.yandex.ru/get/50936/10713508.2341/0_f6abb_45be1c77_S.jpg"
    end
    self.save
  end

	def domain_get_emails
    page = 1
    loop do
      request = RestClient::Request.execute(method: :get, url: "https://pddimp.yandex.ru/api2/admin/email/list?domain=#{self.domainname}&page=#{page}&on_page=100", headers: { PddToken: "#{self.domaintoken2}" })
      break if JSON.parse(request)['accounts'].size == 0
      JSON.parse(request)['accounts'].each do |m|
          newemail = self.emails.new
          newemail.mailname = m['login'].split("@")[0]
          newemail.uid = m['uid']
          newemail.fname = m['fname']
          newemail.iname = m['iname']
          newemail.birth_date = "#{m['birth_date']}"
          newemail.sex = m['sex'].to_s
          newemail.hintq = m['hintq']
          m['enabled'] == "yes" ? newemail.enabled = 1 : newemail.enabled = 0
          JSON.parse(m['aliases'].to_s).each do |aliaz|
            newemail.aliases << aliaz
          end
          newemail.fio = m['fio']
          m['maillist'] == "yes" ? newemail.maillist = 1 : newemail.maillist = 0
          m['ready'] == "yes" ? newemail.signed_eula = 1 : newemail.signed_eula = 0
          get_filters(newemail)
          newemail.save
        end
        page += 1
      end
  end
  
  def get_filters(email)
    q = Hash.from_xml(Nokogiri::Slop(email.domain.get_forward_list(email)).to_s)
    if q.fetch('page', 'no page').fetch('ok', 'not ok').fetch('filters', 'no filters') != nil
      @filters = q.fetch('page', 'no page').fetch('ok', 'not ok').fetch('filters', 'no filters').fetch('filter', 'no filter')    
    else
      @filters = []
    end     
    if @filters.class != Array
      @filters = [@filters]
    end
    @filters = @filters.sort_by{|item| item["filter_param"]}
    email.fwdto = []
    @filters.each do |fltr|
      email.fwdto << fltr['filter_param']
    end
  end

  def get_forward_list(email)
    require 'rest-client'
    require 'active_support/core_ext/hash'  #from_xml 
    require 'nokogiri'
    request = RestClient::Request.execute(method: :get, url: "https://pddimp.yandex.ru/get_forward_list.xml?token=#{self.domaintoken}&login=#{email.mailname}")
  end

end

app/controllers/domains/application_controller.rb
class Domains::ApplicationController < ApplicationController

end

app/controllers/domains/domains_controller.rb
require 'yapdd_api'

class Domains::DomainsController < Domains::ApplicationController
  before_action :set_domain, only: [:edit, :update, :show, :index, :dashboard, :refresh, :kill_filter, :add_filter, :kill_that_mail, :block_that_mail, :unblock_that_mail, :set_current_email]
  before_action :set_domains, only: [:dashboard, :new, :create]
  before_action :set_email, only: [:edit, :update, :show, :dashboard]
  before_action :set_tab
  
  def index
  end

  def dashboard
    redirect_to new_domain_path if current_user.domains.empty?
    #redirect_to new_email_path if current_user.domains.emails.empty?
  end

  def show
  end

  def new
    @domain = Domain.new
  end

  def create
    @domain = current_user.domains.new(domain_params)
    if @domain.save
      flash[:success] = "Домен добавлен!"
      @domain.refresh_emails
      session[:current_domain] = @domain.id
      session[:tab] = 'info'
      redirect_to root_path
    else
      flash[:danger] = "Заполнено не всё, что требуется!"
      render :new
    end
  end

  def edit
  end

  def update
    if @domain.update(domain_params)
      flash[:success] = "Домен успешно отредактирован"
      redirect_to profile_path
    else
      flash[:danger] = "Что-то пошло не так"
      redirect_to profile_path
    end
  end

  def destroy
    @domain = Domain.find_by_id(params[:id])
    @domain.emails.each do |bb|
      bb.destroy
    end
    if @domain.user = current_user
      @domain.destroy
      flash[:success] = "Домен удалён!"
      redirect_to profile_path
    else
      flash[:danger] = "Не твоё - не тронь!"
      redirect_to profile_path
    end
  end

  def refresh
    @domain.refresh_emails
    session[:current_email] = nil
    session[:tab] = "info"
    flash[:success] = "Информация обновлена"
    redirect_to root_path
  end

  def change_domain
    if params[:id] == nil
      redirect_to root_path
    else
      @domain = Domain.find(params[:id])
    end
    if @domain.user == current_user
      session[:current_domain] = @domain.id
      session[:tab] = "info"
      if @domain.emails.first != nil
        session[:current_email] = @domain.emails.order(:mailname).first.id
      end
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
  
  def change_tab
    session[:tab] = params[:id]
    redirect_to root_path
  end

  private
  
  def domain_params
    params.require(:domain).permit(:domainname, :domaintoken, :domaintoken2)
  end

  def set_domain
    if session[:current_domain] != nil
      if Domain.find_by_id(session[:current_domain])
        @domain = Domain.find_by_id(session[:current_domain])
      else
        session[:current_domain] = nil
      end
    elsif session[:current_domain] == nil
      @domain = current_user.domains.first
    end
    if @domain == nil
      redirect_to new_domain_path
    else
      if @domain.user != current_user
        session[:current_domain] = nil
        render status: 403, layout: false
      else
        session[:current_domain] = @domain.id      
      end    
    end
  end

  def set_domains
    @domains = current_user.domains
  end
  
  def set_email
    if @domain.emails.empty?
      session[:tab] = "new_email"
      redirect_to new_email_path
    end
    if session[:current_email] != nil
      if @domain.emails.find_by_id(session[:current_email])
        @email = @domain.emails.find(session[:current_email])
      else
        session[:current_email] = nil
      end
    else
      @email = @domain.emails.order(:mailname).first
      session[:current_email] = @email.id
    end    
  end

  def set_tab
    if (session[:tab] == nil) and (@email != nil)
      session[:tab] = "info"
    end
    if @email == nil
      session[:tab] = "new_mail"
    end
  end

end

app/controllers/domains/emails_controller.rb
require 'yapdd_api'
require 'uri'

class Domains::EmailsController < Domains::ApplicationController

  before_action :set_domain, only: [:get_inside_mail, :kill_that_mail, :new, :create, :add_filter, :update, :add_alias, :kill_alias]
  before_action :set_domains, only: [:new, :update]
  before_action :set_email, only: [:get_inside_mail, :kill_that_mail, :update]
  before_action :set_tab

  def get_inside_mail
    link = YapddAPI.new.get_inside_mailbox(@email)
    redirect_to link
  end
 
  def set_current_email
    if Email.find(params[:id]).domain.user == current_user
      session[:current_email] = params[:id]
      redirect_to root_path
    else
      render status: 403, layout: false
    end    
  end
  
  def show    
  end

  def new
    @email = Email.new
    session[:tab] = "new_email"
    render 'domains/domains/dashboard'
  end
  
  def create
    @email = @domain.emails.new(email_params)
    request = RestClient.get("https://pddimp.yandex.ru/reg_user_token.xml?token=#{@email.domain.domaintoken}&u_login=#{@email.mailname}&u_password=#{@email.pswrd}")
    result = Hash.from_xml(Nokogiri::Slop(request).to_s)
    if result.fetch("page").fetch("error", false)
      if result.fetch("page", "page").fetch("error", "error").fetch("reason", "reason") == "no_address"
        flash[:danger] = "Какая-то фигня с адресом :( (#{result})"
      else
        flash[:danger] = "Что-то пошло не так! (#{result})"
      end
    elsif result.fetch("page").fetch("ok")
        @email.uid = result.fetch("page").fetch("ok").fetch("uid")
    end
    
    url_custom = "https://pddimp.yandex.ru/api2/admin/email/edit?domain=#{@email.domain.domainname}&login=#{@email.mailname}"
    url_custom = url_custom + "&password=#{@email.pswrd}" if @email.pswrd.present?
    url_custom = url_custom + "&iname=#{@email.iname}" if @email.iname.present?
    url_custom = url_custom + "&fname=#{@email.fname}" if @email.fname.present?
    url_custom = url_custom + "&birth_date=#{@email.birth_date.strftime('%F')}" if @email.birth_date.present?
    url_custom = url_custom + "&hintq=#{@email.hintq}" if @email.hintq.present?
    url_custom = url_custom + "&hinta=#{@email.hinta}" if @email.hinta.present?
    url_custom = url_custom + "&sex=#{@email.sex}" if @email.sex.present?

    url = URI::encode(url_custom)
    request = RestClient::Request.execute(method: :post, url: url, headers: { PddToken: "#{@email.domain.domaintoken2}" })
    @result = JSON.parse(request)
    
    puts "---------"
    puts url_custom
    puts "---------"
    puts url
    puts "---------"
    puts @result.to_s
    puts "---------"
    
    @email.enabled = true
    
    if @email.save
      session[:tab] = "info"
      session[:current_email] = @email.id
      flash[:success] = "Ящик добавлен!"
      redirect_to root_path
    else
      errors = ""
      @email.errors.full_messages.each do |err|
        errors = errors + err + "\n"
      end
      flash[:danger] = "Что-то пошло не так!\n#{errors}"
      redirect_to new_email_path
    end
  end

  def update
    if @email.update(email_params)
      flash[:success] = "Мыло успешно отредактировано"
      session[:tab] = "info"
      session[:current_email] = @email.id
    else
      flash[:danger] = "Что-то пошло не так"
    end

    url_custom = "https://pddimp.yandex.ru/api2/admin/email/edit?domain=#{@email.domain.domainname}&login=#{@email.mailname}"
    url_custom = url_custom + "&password=#{@email.pswrd}" if @email.pswrd.present?
    url_custom = url_custom + "&iname=#{@email.iname}" if @email.iname.present?
    url_custom = url_custom + "&fname=#{@email.fname}" if @email.fname.present?
    url_custom = url_custom + "&birth_date=#{@email.birth_date.strftime('%F')}" if @email.birth_date.present?
    url_custom = url_custom + "&hintq=#{@email.hintq}" if @email.hintq.present?
    url_custom = url_custom + "&hinta=#{@email.hinta}" if @email.hinta.present?
    url_custom = url_custom + "&sex=#{@email.sex}" if @email.sex.present?

    url = URI::encode(url_custom)
    request = RestClient::Request.execute(method: :post, url: url, headers: { PddToken: "#{@email.domain.domaintoken2}" })
    @result = JSON.parse(request)

    puts "---------"
    puts url_custom
    puts "---------"
    puts url
    puts "---------"
    puts @result.to_s
    puts "---------"
    
    redirect_to root_path
  end

  def kill_that_mail
    url = "https://pddimp.yandex.ru/api2/admin/email/del?domain=#{@email.domain.domainname}&login=#{@email.mailname}"
    request = RestClient::Request.execute(method: :post, url: url, headers: { PddToken: "#{@email.domain.domaintoken2}" })
    session[:current_email] = nil
    @email.destroy
    redirect_to root_path
  end

  def change_block_status
    email = Email.find_by_id(params[:id])
    if email.domain.user == current_user
      if email.enabled
        newstatus = "no"
        email.enabled = false
      else
        newstatus = "yes"
        email.enabled = true
      end
      email.save
      url = "https://pddimp.yandex.ru/api2/admin/email/edit?domain=#{email.domain.domainname}&login=#{email.mailname}&enabled=#{newstatus}"
      request = RestClient::Request.execute(method: :post, url: url, headers: { PddToken: "#{email.domain.domaintoken2}" })
      flash[:success] = "Статус успешно изменён на #{newstatus}"
      redirect_to root_path
    else
      render status: 403, layout: false
    end
  end

  def kill_filter
    email = Email.find(session[:current_email])
    request = RestClient.get("https://pddimp.yandex.ru/delete_forward.xml?token=#{email.domain.domaintoken}&login=#{email.mailname}&filter_id=#{params[:id]}")
    result = Hash.from_xml(Nokogiri::Slop(request).to_s)
    if result.fetch("page").fetch("error", false)
      if result.fetch("page", "page").fetch("error", "error").fetch("reason", "reason") == "no_address"
        flash[:danger] = "Какая-то фигня с адресом :("
      else
        flash[:danger] = "Что-то пошло не так! (#{result})"
      end
    else
      flash[:success] = "Удалил!"
    end
    redirect_to root_path
  end

  def add_filter
    email = Email.find(session[:current_email])
    request_url = "https://pddimp.yandex.ru/set_forward.xml?token=#{@domain.domaintoken}&login=#{email.mailname}&address=#{params[:address]}&copy=yes"
    request = RestClient.get(request_url)
    result = Hash.from_xml(Nokogiri::Slop(request).to_s)
    if result.fetch("page").fetch("error", false)
      if result.fetch("page", "page").fetch("error", "error").fetch("reason", "reason") == "no_address"
        flash[:danger] = "Не могу поставить перадресацию на такой адрес! :("
      else
        flash[:danger] = "Что-то пошло не так! (#{result})"
      end
    else
      flash[:success] = "Вроде, получилось!"
    end
    redirect_to root_path
  end

  def add_alias # не работает
    email = Email.find(session[:current_email])
    new_alias = params[:new_alias]
    aliazez = []
    @domain.emails.each do |al|
      if al.aliases.size > 0
        aliazez << al.aliases
      end
    end
    not_in_aliases = true
    aliazez.each do |qq|
      if qq.split('@')[0] == new_alias.split('@')[0]
        not_in_aliases = false
      end
    end
    if @domain.emails.find_by(mailname: new_alias.split('@')[0]) != nil && not_in_aliases
      flash[:danger] = "Такой адрес уже есть :/"
      redirect_to root_path
    else
      email.aliases << (new_alias + "@" + @domain.domainname)
      email.save
      flash[:success] = "Вроде, получилось!"
      redirect_to root_path
    end
  end

  def kill_alias
    email = Email.find(session[:current_email])
  end
  
private

  def email_params
    params.require(:email).permit(:mailname, :iname, :fname, :pswrd, :birth_date, :hintq, :hinta, :sex)
  end
  
  def set_email
    @email = @domain.emails.find_by_id(params[:id])
    if @email.domain.user != current_user
      render status: 403, layout: false
      @email = nil
    end
  end

  def set_domain
    if session[:current_domain] != nil
      @domain = Domain.find(session[:current_domain])
    else
      @domain = current_user.domains.first
      session[:current_domain] = @domain.id      
    end
    if @domain.user != current_user
      session[:current_domain] = nil
      render status: 403, layout: false
    end    
  end
  
  def set_tab
    if session[:tab] == nil
      session[:tab] = "info"
    end
  end

  def set_domains
    @domains = current_user.domains
  end
  
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/domains/_form.html.slim
h1
  small
    | все поля обязательны для заполнения
.row
  .well.col-md-8.col-md-offset-2
    = form_for(@domain, html: { multipart: true }) do |f|
      = f.label "Имя домена:"
      = f.text_field :domainname
      = f.label 'Токен API: '
      br
      small
        | (получить его можно 
        a[href="https://pddimp.yandex.ru/get_token.xml"]
          | здесь
        | )
      = f.text_field :domaintoken
      = f.label 'Токен API2: '
      br
      small
        | (получить его можно 
        a[href="https://pddimp.yandex.ru/api2/admin/get_token"]
          | здесь
        | )
      = f.text_field :domaintoken2
      = f.submit(@domain.new_record? ? 'Добавить' : 'Сохранить', class: "btn btn-success")

= render 'shared/errors', obj: @domain

app/views/domains/domains/_form_domains.html.slim
| ﻿
= render 'shared/errors', obj: domain
.row
  .well.col-md-8.col-md-offset-2
    = form_for(domain, url: update_domain_path(domain), html: {multipart: true, method: 'patch'}) do |f|
      = f.label "Имя домена:"
      = f.text_field :domainname
      = f.label 'Токен API: '
      br
      small
        | (получить его можно 
        a[href="https://pddimp.yandex.ru/get_token.xml"]
          | здесь
        | )
      = f.text_field :domaintoken
      = f.label 'Токен API2: '
      br
      small
        | (получить его можно 
        a[href="https://pddimp.yandex.ru/api2/admin/get_token"]
          | здесь
        | )
      = f.text_field :domaintoken2
      = f.submit('Сохранить', class: "btn btn-success")

      = link_to "Удалить", delete_domain_path(domain), class: "pull-right", title: "Забыть инфу об этом домене", data: { confirm: "Точно хотите удалить из базы домен #{domain.domainname}?" }

app/views/domains/domains/_forward.html.slim
= render 'shared/errors', obj: @domain
.row
  .col-md-6
    h4
      | Переадресации ящика 
      = @email.mailname + "@" + @domain.domainname
      | :
    ul.list-group
      - get_filters(@email)
      - @email.save
      - if @filters.size == 0
        br
        = "Переадресаций не установлено"
      - @filters.each do |fltr|
        li class="list-group-item"
          - if fltr['filter_param'].split('@')[1] == @domain.domainname
            - mail_id = @domain.emails.find_by(mailname: fltr['filter_param'].split('@')[0])
            => link_to fltr['filter_param'], set_current_email_path(mail_id.id)
          - else
            => fltr['filter_param']
          span class="badge pull-right"
            = link_to " ", kill_filter_path(fltr['id']), class: "glyphicon glyphicon-remove", title: "Удалить переадресацию", data: { confirm: "Точно хотите удалить переадресацию на #{fltr['filter_param']}?" }
    form[action="/add_filter/"]
      .input-group
        span#basic-addon1.input-group-addon
          | @
        | <input type="hidden" name="email" value="
        = params[:address]
        | "> 
        input.form-control[type="text" placeholder="Куда переадресовать?" aria-describedby="basic-addon1" name="address"]
        input.button[type="submit" value="Плюх" style="display:none;"]
    |  <a href="/addfilter/?&email=
    = :address
    | "> </a>
  .col-md-5
    h4
      | Входящие переадресации<br>
      small
        | поиск ведётся по всем подключенным к вашему аккаунту доменам
    ul.list-group
      - incoming(@email)
      - if @incomefwd.size == 0
        br
        | Никто не переадресовывает свою почту на этот ящик
      - @incomefwd.each do |fltr|
        li class="list-group-item"
          - if fltr.split('@')[1] == @domain.domainname
            - mail_id = @domain.emails.find_by(mailname: fltr.split('@')[0])
            => link_to fltr, set_current_email_path(mail_id.id)
          - else
            => fltr
            

app/views/domains/domains/_info.html.slim
= render 'shared/errors', obj: @domain
h4
  = "Ящик " + @email.mailname + "@" + @email.domain.domainname + ":"
.row
  - if @email.maillist != true
    = render 'domains/emails/email_update_form'
    .well.col-md-5
      h4
        | Суммарная информация:
      p
        | <b>Имя: </b>
        = @email.iname.presence ? (@email.iname) : "хз"
      p
        | <b>Фамилия: </b>
        = @email.fname.presence ? (@email.fname) : "хз"
      p
        | <b>ФИО: </b>
        = @email.fio.presence ? (@email.fio) : "хз"
      p
        | <b>День рождения: </b>
        = @email.birth_date.presence ? (@email.birth_date) : "хз"
      p
        | <b>Секретный вопрос: </b>
        = @email.hintq.presence ? (@email.hintq) : "хз"
      p
        | <b>Пол: </b>
        = (@email.sex == "1") ? 'мужской' : ((@email.sex == "2") ? 'женский' : 'всё сложно')
      p
        | <b>Фурычит ли: </b>
        => @email.enabled ? "да" : "нет"
        => link_to " ", change_block_status_path(@email.id), class: "glyphicon glyphicon-off spaceright", title: "Вкл/выкл ящика", data: { confirm: "Точно хотите сменить статус блокировки у #{@email.mailname}@#{@domain.domainname}?" }
      p
        | <b>Готов ли к работе: </b>
        = @email.signed_eula.presence ? "да" : "хз"
      p
        | <b>Псевдонимы: </b>
        - if @email.aliases.present?
          - @email.aliases.each do |a|
            = "#{a} "
            => link_to " ", "#", class: "glyphicon glyphicon-remove spaceright", title: "Удалить псевдоним", data: { confirm: "К сожалению, никак. Эту возможность Яндекс даёт только в собственной админке :(" }
        - else
          | нет
        /form[action="/add_alias/"]
          .input-group
            span#basic-addon1.input-group-addon
              | @
            | <input type="hidden" name="new_alias" value="
            = params[:new_alias]
            | "> 
            input.form-control[type="text" placeholder="новый псевдоним" aria-describedby="basic-addon1" name="new_alias"]
            input.button[type="submit" value="Плюх" style="display:none;"]
        /|  <a href="/add_alias/?&new_alias=
        /= :new_alias
        /| "> </a>
      p
        | * добавление и удаление псевдонимов доступно только в 
        => link_to "официальной", "https://pdd.yandex.ru/domain/#{@domain.domainname}/"
        | админке Яндекса.
      hr
      p
        |  Информация обновлена: 
        = @email.updated_at
      hr
        | ** Пароль и ответ на секретный вопрос безвозвратно забываются при обновлении инфрмации о ящиках
  - else
    h3
      | Это специальный адрес для рассылки. Есть смысл перейти во вкладку "Переадресация"

app/views/domains/domains/dashboard.html.slim
/= render "shared/errors", obj: @domain
/= render "shared/errors", obj: @email
= render "shared/page_title", title: "Домен #{@domain.domainname}"

.row
  .col-md-3
    .show_domain
      => "Ящиков в " + @domain.domainname + ":"
      => @domain.emails.size
      span class="pull-right"
        => link_to " ", refresh_domain_path(@domain), class: "glyphicon glyphicon-refresh", title: "Обновить информацию о ящиках в этом домене"
        => link_to " ", new_email_path, class: "glyphicon glyphicon-plus", title: "Добавить новый email"
      div id="emailslist"
        input type="text" class="fuzzy-search" placeholder="Поиск среди живых"
        ul class="list list-group"
          - @domain.emails.order("mailname").each do |email|
            li class="list-group-item mailsfix"
              p class="name"
                - if email.enabled == false
                  - if email == @email
                    = link_to email.mailname, set_current_email_path(email.id), class: "disabled bold"
                  - else
                    = link_to email.mailname, set_current_email_path(email.id), class: "disabled"
                - else
                  - if email == @email
                    = link_to email.mailname, set_current_email_path(email.id), class: "bold"
                  - else
                    = link_to email.mailname, set_current_email_path(email.id)
                span class="badge pull-right"
                  | <a class="btn-clipboard glyphicon glyphicon-copy spaceright", data-clipboard-text="
                  = "#{email.mailname}@#{email.domain.domainname}"
                  |", title="Скопировать в буфер обмена">  </a>
                  => link_to " ", get_inside_mail_path(email.id), class: "glyphicon glyphicon-envelope spaceright", target: "_blank", title: "Войти в этот ящик"
                  => link_to " ", change_block_status_path(email.id), class: "glyphicon glyphicon-off spaceright", title: "Вкл/выкл ящика", data: { confirm: "Точно хотите сменить статус блокировки у #{email.mailname}@#{@domain.domainname}?" }
                  => link_to " ", kill_that_mail_path(email.id), class: "glyphicon glyphicon-remove", title: "Прибить ящик", data: { confirm: "Точно хотите убить, а не заблокировать ящик #{email.mailname}?" }
      - if @domain.emails.size == 0
        hr
          b
            = "В домене #{@domain.domainname} нет ни одного ящика. Если Вы их уже создали, попробуйте " 
            = link_to "обновить", refresh_domain_path(@domain)
            = " список ящиков"
  .col-md-8
    = render 'layouts/tabs'

script src="https://cdnjs.cloudflare.com/ajax/libs/list.fuzzysearch.js/0.1.0/list.fuzzysearch.js"
script
  | new Clipboard('.btn-clipboard');
script
  | var monkeyList = new List('emailslist', { 
  | valueNames: ['name'], 
  | plugins: [ ListFuzzySearch() ] });

app/views/domains/domains/index.html.slim
| ﻿
- if (@domains.where(user: current_user).size == 0) then (redirect_to add_domain_path) end
  = render 'shared/page_title', title: "Домен #{@domain.domainname}"
  - # will_paginate
  .row
    .col-md-3
      .show_domain
        ul.list-group
          - @domain.emails.order("mailname").each do |email|
            li.list-group-item.mailsfix
              span.badge.pull-right
                | <a class="glyphicon glyphicon-envelope spaceright" href="/get_inside_mail/?domain=
                = @domain.domainname
                | &email=
                = email.mailname
                | " target="_blank" title="Войти в этот ящик"> 
                |  <a onclick="if(!confirm('Вы точно хотите безвозвратно удалить ящик 
                = email.mailname
                | ?')){return false;}" class="glyphicon glyphicon-remove spaceright" href="/kill_that_mail/?domain=
                = @domain.domainname
                | &email=
                = email.mailname
                | " target="_blank" title="Удалить этот ящик"> 
                |  <a onclick="if(!confirm('Вы точно хотите заблокировать ящик 
                = email.mailname
                | ?')){return false;}" class="glyphicon glyphicon-off spaceright" href="/
                = if (email.enabled == false) then "un" end
                | block_that_mail/?domain=
                = @domain.domainname
                | &email=
                = email.mailname
                | " target="_blank" title="Заблокировать этот ящик"> 
              |  <span class="
              - if email.enabled == false
                | disabledmail
              | ">
              = link_to email.mailname, domains_path("domain" => @domain.domainname, "email" => email.mailname, "tab" => ((params[:tab]) ? (params[:tab]) : "info"))
    .col-md-8
      = render 'layouts/tabs'
  - # will_paginate

app/views/domains/domains/new.html.slim
| ﻿
= render 'shared/errors', obj: @domain
= render 'shared/page_title', title: "Добавить домен"
= render 'form'

app/views/domains/domains/show.html.slim
- # render 'shared/page_title', title: @domain.domainname
h1
  = @domain.domainname
  = link_to " ", edit_domain_path(@domain), class: "glyphicon glyphicon-pencil"
  = link_to " ", refresh_domain_path(@domain), class: "glyphicon glyphicon-refresh"
  - # link_to "Удалить", delete_domain_path(@domain), method: :delete, data: {confirm: "Точно? О_о"}, class: "glyphicon glyphicon-remove"
.row
  .col-md-8
    .show_recipe
      - @domain.domain_get_image_url(@domain) if @domain.image
      = image_tag(@domain.image, class: "gravatar")
      - @domain.domain_get_emails(@domain) if @domain.emails
      - @domain.emails.each do |q|
        ul
          li
            = q.mailname