config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated :user do
    root 'domains/domains#dashboard', as: :authenticated_root
  end

  root to: 'pages#welcome'

  scope module: 'domains' do
    resources :domains do
    resources :emails, shallow: true 
    end
  end

  get 'refresh/:id', to: "domains/domains#refresh", as: 'refresh_domain'
  get 'get_inside_mail/:id', to: "domains/emails#get_inside_mail", as: 'get_inside_mail'
  get 'change_block_status/:id', to: "domains/emails#change_block_status", as: 'change_block_status'
  get 'change_domain/:id', to: "domains/domains#change_domain", as: 'change_domain'
  get 'set_current_email/:id', to: "domains/emails#set_current_email", as: 'set_current_email'
  get 'change_tab/:id', to: "domains/domains#change_tab", as: 'change_tab'
  get 'kill_filter/:id', to: "domains/emails#kill_filter", as: 'kill_filter'
  get 'add_filter', to: "domains/emails#add_filter"
  get 'email/new', to: "domains/emails#new", as: 'new_email'
  post 'email/new', to: "domains/emails#create"
  get 'kill_that_mail/:id', to: "domains/emails#kill_that_mail", as: 'kill_that_mail'
  get 'profile', to: "users#profile", as: 'profile'
  get 'delete_domain/:id', to: "domains/domains#destroy", as: 'delete_domain'
  get 'faq', to: "pages#faq", as: 'faq'
  patch 'update_domain/:id', to: "domains/domains#update", as: 'update_domain'
  patch 'update_email/:id', to: "domains/emails#update", as: 'update_email'
  get 'add_alias', to: "domains/emails#add_alias", as: "add_alias"
  get 'kill_alias', to: "domains/emails#kill_alias", as: "kill_alias"

end

app/views/layouts/_footer.html.slim
.footer
  p
    | © 
    = link_to "megashurik", "http://vk.com/megashurik"
    | , 2016

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-default
  .container
    = link_to "ЯПДД", root_path, class: "btn btn-lg btn-success", id: "logo"
    - if user_signed_in?
      ul.nav_item
        li.dropdown
          a.btn.btn-default.dropdown-toggle[data-toggle="dropdown"]
            => @domain.domainname
            b.caret
          ul.dropdown-menu
            - @domains.order(:domainname).each do |d|
              li
                = link_to d.domainname, change_domain_path(d.id)
            li.divider
            li
              = link_to "Добавить домен", new_domain_path
    - if user_signed_in?
      ul.nav_item.navbar-right
        li.dropdown.tolefton15
          a.btn.btn-danger.dropdown-toggle[data-toggle="dropdown"]
            b => current_user.name
            b.caret
          ul.dropdown-menu
            li
              = link_to "Управление доменами", profile_path
            li
              = link_to "FAQ", faq_path
            li
              = link_to "Подключить домен к Яндексу", "https://pdd.yandex.ru/domains_add/"
            li
              = link_to "Редактор DNS #{@domain.domainname}", "https://pdd.yandex.ru/domain_ns/#{@domain.domainname}/"
            li.divider
            li
              = link_to "Выйти", destroy_user_session_path, method: :delete
    - else
      ul.nav_item.navbar-right.tolefton15
        li.inline-button
          = link_to "FAQ", faq_path, class: "btn btn-success"
        li.inline-button
          = link_to "Зарегистрироваться", new_user_registration_path, class: "btn btn-success"
        li.inline-button
          = link_to "Войти", new_user_session_path, class: "btn btn-success"

app/views/layouts/_messages.html.slim
#message.row.alert-message[style="display:none;"]
  .col-md-10
    - flash.each do |message_type, message|
      | <div class="alert alert-
      = message_type
      | ">
      = message
script
  |  window.onload=function() { $("#message").fadeIn(1000).delay(6000).fadeOut(700); }; 

app/views/layouts/_tabs.html.slim
ul.nav.nav-tabs
  |  <li
  - if session[:tab] == "info" or session[:tab] == nil
    |  class="active" 
  | > 
  = link_to "Информация", controller: "domains/domains", action: "change_tab", id: "info"

  | </li> <li
  - if session[:tab] == "new_email"
    |  class="active" 
  | > 
  = link_to "Новый ящик", controller: "domains/emails", action: "new"
  | </li> <li
  - if session[:tab] == "forward"
    |  class="active" 
  | > 
  = link_to "Переадресация", controller: "domains/domains", action: "change_tab", id: "forward"
  | </li>
= render_content

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Yapdd
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    div.container
      = render 'layouts/header'
      = yield
      = render 'layouts/footer'
      = render 'layouts/messages'